### ISSUE TITLE
program only work when I open the window

### ISSUE THREAD

**Issue by Kurisunyanyan** [Yonisen/WarThunder_Yellow_Mark_Rangefinder#2]
When I press any key in the game the program won't run, but it works when I bring the window to the front.
![01](https://github.com/Yonisen/WarThunder_Yellow_Mark_Rangefinder/assets/108979957/d8ba8aec-a3e1-4d18-aab8-735e9bd5ae17)

**Comment by Yonisen** [comment]
are you running the game in fullscreen windowed mode?
Are you running the game as an administrator?
is this the steam version?

**Comment by Kurisunyanyan** [comment]
> 
Thanks for your reply. In fact, I tried to use some scripts to listen Global Hotkey, but keyboard operations cannot be recorded while WT and some other programs are running. Also, I run the game by steam in full screen window mode, but not run as administrator.

**Comment by Yonisen** [comment]
the only thing i can suggest is to install warthunder without steam

**Comment by Langyinnan** [comment]
I'm running the game in fullscreen mode, not fullscreen windowed mode, it's the steam version, and yellow ranging it's useful
